version: "3.9"

services:
  nginx:
    container_name: safety-vision-nginx
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./data/nginx/dev:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - web
      - ui
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'safety-vision-platform-db'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db:/var/lib/mysql
  web:
    image: safety-vision-platform_web-local
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-b4^apzjzd^*j3e%mk%6g+01c=%wro97mdcesysh)l9j*h6#3tf
      - DEBUG=True
      - ALLOWED_HOSTS=web
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=safety-vision-platform-db
      - CREATE_INFRACTION_EVENT_KEY=token
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    links:
      - localstack
    volumes:
      - ../safety-vision-platform:/code
    expose:
      - 8000
    depends_on:
      - db
  ui:
    image: safety-vision-platform_ui-local
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../safety-vision-ui:/code
    expose:
      - 3000
    depends_on:
      - db
      - web
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localhost
      - HOSTNAME=localhost
      - USE_SSL=false
      - DATA_DIR=${LOCALSTACK_DATA_DIR:-/tmp/localstack/data}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack:/docker-entrypoint-initaws.d
      - ./localstack_data:/tmp/localstack
volumes:
  db:
