version: "3.9"

services:
  reverse_proxy:
    container_name: safety-vision-nginx
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web
      - ui
  web:
    image: safetyvision/safety-vision-platform
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    environment:
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - DATABASE_HOST
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_NAME
      - AWS_S3_ACCESS_KEY_ID
      - AWS_S3_SECRET_ACCESS_KEY
    expose:
      - 8000
  ui:
    image: safetyvision/safety-vision-ui
    command: npm start
    expose:
      - 3000
    depends_on:
      - web
